# Generated by Django 3.0.1 on 2019-12-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=120)),
                ('desc_produto', models.TextField()),
                ('preço_produto', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
            ],
        ),
    ]
