# Generated by Django 3.0.1 on 2019-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_produto',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
