# Generated by Django 3.0.1 on 2019-12-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtoapp', '0002_produto_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
