# Generated by Django 3.0.1 on 2019-12-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtoapp', '0004_auto_20191219_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
